# Generated by Django 5.2.7 on 2025-10-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.AutoField(db_column='NOTIF_ID', primary_key=True, serialize=False)),
                ('notif_title', models.CharField(db_column='NOTIF_TITLE', max_length=255)),
                ('notif_message', models.TextField(db_column='NOTIF_MESSAGE')),
                ('notif_type', models.CharField(choices=[('system', 'System'), ('chat', 'Chat'), ('report', 'Report'), ('payment', 'Payment'), ('listing', 'Listing'), ('review', 'Review'), ('verification', 'Verification')], db_column='NOTIF_TYPE', max_length=20)),
                ('link_url', models.CharField(blank=True, db_column='LINK_URL', max_length=255, null=True)),
                ('is_read', models.BooleanField(db_column='IS_READ', default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CREATEDAT')),
                ('read_at', models.DateTimeField(blank=True, db_column='READ_AT', null=True)),
            ],
            options={
                'db_table': 'NOTIFICATIONS',
                'ordering': ['-createdat'],
            },
        ),
    ]
