# Generated by Django 5.2.7 on 2025-10-17 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['userid'], name='NOTIFICATIO_USERID_1951cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='NOTIFICATIO_IS_READ_d2f923_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notif_type'], name='NOTIFICATIO_NOTIF_T_dcbedd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['createdat'], name='NOTIFICATIO_CREATED_bd17f0_idx'),
        ),
    ]
