# Generated by Django 5.2.7 on 2025-10-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('dealerapp_id', models.AutoField(db_column='DEALERAPP_ID', primary_key=True, serialize=False)),
                ('business_name', models.CharField(db_column='BUSINESS_NAME', max_length=255)),
                ('business_type', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('both', 'Both')], db_column='BUSINESS_TYPE', max_length=20)),
                ('business_address', models.TextField(db_column='BUSINESS_ADDRESS')),
                ('business_phone', models.CharField(blank=True, db_column='BUSINESS_PHONE', max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, db_column='BUSINESS_EMAIL', max_length=254, null=True)),
                ('tax_id', models.CharField(blank=True, db_column='TAX_ID', max_length=100, null=True)),
                ('business_license', models.CharField(blank=True, db_column='BUSINESS_LICENSE', max_length=100, null=True)),
                ('appli_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_column='APPLI_STATUS', default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, db_column='REJECTION_REASON', null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CREATEDAT')),
                ('approvedat', models.DateTimeField(blank=True, db_column='APPROVEDAT', null=True)),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='UPDATEDAT')),
            ],
            options={
                'db_table': 'DEALER_APPLICATIONS',
            },
        ),
        migrations.CreateModel(
            name='DealerDocument',
            fields=[
                ('dealerdoc_id', models.AutoField(db_column='DEALERDOC_ID', primary_key=True, serialize=False)),
                ('doc_type', models.CharField(db_column='DOC_TYPE', max_length=255)),
                ('file_url', models.CharField(db_column='FILE_URL', max_length=255)),
                ('file_size', models.IntegerField(blank=True, db_column='FILE_SIZE', null=True)),
                ('verified', models.BooleanField(db_column='VERIFIED', default=False)),
                ('uploadedat', models.DateTimeField(auto_now_add=True, db_column='UPLOADEDAT')),
            ],
            options={
                'db_table': 'DEALER_DOCUMENTS',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(db_column='PAYMENT_ID', max_length=64, primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(db_column='PAYMENT_AMOUNT', decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('wallet', 'Wallet')], db_column='PAYMENT_METHOD', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_column='PAYMENT_STATUS', default='pending', max_length=20)),
                ('payment_ref', models.CharField(db_column='PAYMENT_REF', max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, db_column='TRANSACTION_ID', max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, db_column='FAILURE_REASON', null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CREATEDAT')),
                ('confirmed_at', models.DateTimeField(blank=True, db_column='CONFIRMED_AT', null=True)),
            ],
            options={
                'db_table': 'PAYMENTS',
            },
        ),
    ]
