# Generated by Django 5.2.7 on 2025-10-17 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerapplication',
            name='userid',
            field=models.OneToOneField(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealerdocument',
            name='dealerapp_id',
            field=models.ForeignKey(db_column='DEALERAPP_ID', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.dealerapplication'),
        ),
        migrations.AddField(
            model_name='payment',
            name='listing_id',
            field=models.ForeignKey(blank=True, db_column='LISTING_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='payment',
            name='pricing_id',
            field=models.ForeignKey(db_column='PRICING_ID', on_delete=django.db.models.deletion.RESTRICT, to='listings.pricingplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['userid'], name='PAYMENTS_USERID_666f02_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_status'], name='PAYMENTS_PAYMENT_fb6bad_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['createdat'], name='PAYMENTS_CREATED_5a0eba_idx'),
        ),
    ]
