# Generated by Django 5.2.7 on 2025-10-17 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='cat_id',
            field=models.ForeignKey(db_column='CAT_ID', on_delete=django.db.models.deletion.RESTRICT, to='listings.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorite',
            name='listing_id',
            field=models.ForeignKey(db_column='LISTING_ID', on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing_id',
            field=models.ForeignKey(db_column='LISTING_ID', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='listing_id',
            field=models.ForeignKey(blank=True, db_column='LISTING_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='reviewed_userid',
            field=models.ForeignKey(db_column='REVIEWED_USERID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportmisconduct',
            name='listing_id',
            field=models.ForeignKey(blank=True, db_column='LISTING_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='reportmisconduct',
            name='reported_userid',
            field=models.ForeignKey(blank=True, db_column='REPORTED_USERID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportmisconduct',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['userid'], name='LISTINGS_USERID_e2e4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['cat_id'], name='LISTINGS_CAT_ID_c38969_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_status'], name='LISTINGS_LISTING_23ea37_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured'], name='LISTINGS_IS_FEAT_78f10a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['list_location'], name='LISTINGS_LIST_LO_3317db_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_price'], name='LISTINGS_LISTING_a164ef_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['createdat'], name='LISTINGS_CREATED_5f490a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('userid', 'listing_id')},
        ),
        migrations.AddIndex(
            model_name='ratingreview',
            index=models.Index(fields=['reviewed_userid'], name='RATINGS_N_R_REVIEWE_49c5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ratingreview',
            index=models.Index(fields=['rating'], name='RATINGS_N_R_RATING_38b197_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingreview',
            unique_together={('userid', 'reviewed_userid', 'listing_id')},
        ),
        migrations.AddIndex(
            model_name='reportmisconduct',
            index=models.Index(fields=['userid'], name='REPORTS_N_M_USERID_d8a655_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmisconduct',
            index=models.Index(fields=['reported_userid'], name='REPORTS_N_M_REPORTE_7824da_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmisconduct',
            index=models.Index(fields=['listing_id'], name='REPORTS_N_M_LISTING_642e60_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmisconduct',
            index=models.Index(fields=['report_status'], name='REPORTS_N_M_REPORT__9b32fd_idx'),
        ),
    ]
