# Generated by Django 5.2.7 on 2025-10-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('subscription_id', models.AutoField(db_column='SUBSCRIPTION_ID', primary_key=True, serialize=False)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_column='SUBSCRIPTION_STATUS', default='active', max_length=10)),
                ('listings_used', models.IntegerField(db_column='LISTINGS_USED', default=0)),
                ('starts_at', models.DateTimeField(db_column='STARTS_AT')),
                ('expires_at', models.DateTimeField(blank=True, db_column='EXPIRES_AT', null=True)),
                ('auto_renew', models.BooleanField(db_column='AUTO_RENEW', default=False)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CREATEDAT')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='UPDATEDAT')),
                ('pricing_id', models.ForeignKey(db_column='PRICING_ID', on_delete=django.db.models.deletion.RESTRICT, to='listings.pricingplan')),
                ('userid', models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_SUBSCRIPTIONS',
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['userid'], name='USER_SUBSCR_USERID_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['subscription_status'], name='USER_SUBSCR_SUBSCRI_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['expires_at'], name='USER_SUBSCR_EXPIRES_idx'),
        ),
    ]
