# Generated by Django 5.2.7 on 2025-10-23 19:18

from django.db import migrations


def create_free_tier_plan(apps, schema_editor):
    """
    Create the free tier pricing plan if it doesn't exist
    """
    PricingPlan = apps.get_model('listings', 'PricingPlan')

    # Check if free tier already exists
    if not PricingPlan.objects.filter(pricing_name='Free Tier').exists():
        PricingPlan.objects.create(
            pricing_name='Free Tier',
            pricing_description='Basic plan with 3 free listings to get started',
            plan_price=0.00,
            duration_days=60,
            category_scope='all',
            max_listings=3,
            max_images_per_listing=5,
            is_featured=False,
            is_active=True
        )


def reverse_create_free_tier_plan(apps, schema_editor):
    """
    Remove the free tier pricing plan
    """
    PricingPlan = apps.get_model('listings', 'PricingPlan')
    PricingPlan.objects.filter(pricing_name='Free Tier').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_usersubscription'),
    ]

    operations = [
        migrations.RunPython(create_free_tier_plan, reverse_create_free_tier_plan),
    ]
