# Generated by Django 5.2.7 on 2025-10-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_create_free_tier_plan'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='USER_SUBSCR_USERID_ec0a40_idx',
            old_name='USER_SUBSCR_USERID_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='USER_SUBSCR_SUBSCRI_b6aa1a_idx',
            old_name='USER_SUBSCR_SUBSCRI_idx',
        ),
        migrations.RenameIndex(
            model_name='usersubscription',
            new_name='USER_SUBSCR_EXPIRES_d3be95_idx',
            old_name='USER_SUBSCR_EXPIRES_idx',
        ),
    ]
