# Generated by Django 5.2.7 on 2025-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_user_subscr_userid_idx_user_subscr_userid_ec0a40_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_price',
            field=models.DecimalField(db_column='LISTING_PRICE', decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='plan_price',
            field=models.DecimalField(db_column='PLAN_PRICE', decimal_places=2, max_digits=12),
        ),
    ]
