# Generated by Django 5.2.7 on 2025-10-29 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_listing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='area_size',
            field=models.DecimalField(blank=True, db_column='AREA_SIZE', decimal_places=2, help_text='Area/size of property or land', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('sqm', 'Square Meters (m²)'), ('hectares', 'Hectares'), ('acres', 'Acres')], db_column='AREA_UNIT', default='sqm', help_text='Unit of area measurement', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, db_column='BATHROOMS', help_text='Number of bathrooms', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, db_column='BEDROOMS', help_text='Number of bedrooms', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], db_column='CONDITION', help_text='Condition of item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('other', 'Other')], db_column='FUEL_TYPE', help_text='Fuel type (for vehicles)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_garage',
            field=models.BooleanField(db_column='HAS_GARAGE', default=False, help_text='Property has a garage'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_garden',
            field=models.BooleanField(db_column='HAS_GARDEN', default=False, help_text='Property has a garden'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(blank=True, db_column='MILEAGE', help_text='Mileage in kilometers (for vehicles)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='parking_spaces',
            field=models.IntegerField(blank=True, db_column='PARKING_SPACES', help_text='Number of parking spaces', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial Property'), ('other', 'Other')], db_column='PROPERTY_TYPE', help_text='Type of property (house, apartment, land, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic')], db_column='TRANSMISSION', help_text='Transmission type (for vehicles)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other Vehicle')], db_column='VEHICLE_TYPE', help_text='Type of vehicle', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='year_built',
            field=models.IntegerField(blank=True, db_column='YEAR_BUILT', help_text='Year built/manufactured', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
