# Generated by Django 5.2.7 on 2025-10-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(db_column='MESSAGE_ID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='CONTENT')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], db_column='MESSAGE_TYPE', default='text', max_length=10)),
                ('file_url', models.CharField(blank=True, db_column='FILE_URL', max_length=255, null=True)),
                ('is_read', models.BooleanField(db_column='IS_READ', default=False)),
                ('sentat', models.DateTimeField(auto_now_add=True, db_column='SENTAT')),
                ('read_at', models.DateTimeField(blank=True, db_column='READ_AT', null=True)),
            ],
            options={
                'db_table': 'MESSAGES',
                'ordering': ['sentat'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(db_column='CHAT_ID', primary_key=True, serialize=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_column='LAST_MESSAGE_AT', null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='CREATEDAT')),
                ('listing_id', models.ForeignKey(db_column='LISTING_ID', on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
            options={
                'db_table': 'CHATS',
            },
        ),
    ]
