# Generated by Django 5.2.7 on 2025-10-17 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='userid_as_seller',
            field=models.ForeignKey(db_column='USERID_AS_SELLER', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.ForeignKey(db_column='CHAT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='userid',
            field=models.ForeignKey(db_column='USERID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message_at'], name='CHATS_LAST_ME_8dc7d4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('userid', 'listing_id', 'userid_as_seller')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_id'], name='MESSAGES_CHAT_ID_97a675_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sentat'], name='MESSAGES_SENTAT_c0bbfc_idx'),
        ),
    ]
